[package]
name = "shiroa-mdbook"
version = "0.2.3"
entrypoint = "lib.typ"
authors = ["Myriad-Dreamin <https://github.com/Myriad-Dreamin>"]
license = "Apache-2.0"
homepage = "https://myriad-dreamin.github.io/shiroa"
repository = "https://github.com/Myriad-Dreamin/shiroa"
keywords = ["book", "web"]
categories = ["book"]
description = "The mdbook theme is a modern, responsive theme for [Shiroa](https://github.com/Myriad-Dreamin/shiroa/), inspired by the mdbook."
